# Generated by Django 2.1.1 on 2019-05-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190502_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='image',
            field=models.ImageField(default='default_project.jpg', upload_to='project_pics'),
        ),
    ]
