# Generated by Django 2.2.1 on 2019-05-02 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20190502_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='participate',
            field=models.ManyToManyField(blank=True, related_name='participate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='projects',
            field=models.ManyToManyField(blank=True, to='accounts.ProjectPage'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creater', to=settings.AUTH_USER_MODEL),
        ),
    ]
